language: julia
os:
  - linux
julia:
  - 0.4.0
notifications:
  email: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy 
 - sudo pip install Cython
 - sudo pip install tifffile

script: ./travis.sh
